image: python:3.7.4
stages:
  - install
  - test

install-dependencies:
  stage: install
  script:
    - pip3 install -q -r requirements.txt

test-app:
  stage: test
  dependencies:
    - install-dependencies
  script:
    - nose2