image: python:3.7.4
stages:
  - test

before_script:
  - python3 --version
  - pip3 install -r requirements.txt

test-app:
  stage: test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python3 -c "import sys;print(sys.path)"
    - nose2 -v --with-coverage project.tests.test_basic